---
title: "week3-lab"
format: html
---

```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                                    setup                                 ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#..........................load packages.........................
library(tidyverse)

#..........................import data...........................
drought <- read_csv(here::here("week3/data/drought.csv"))

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                            wrangle drought data                          ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drought_clean <- drought |>
  
  # Pivot table to be in tidy form
  pivot_longer(cols = None:D4, names_to = "drought_lvl",    values_to = "area_pct") |>
  
  janitor::clean_names() |>
  
  # Rename state abbreviation column
   rename(state_abb = state_abbreviation) |>

  # select cols of interest & update names for clarity (as needed) ----
  select(date = valid_start, state_abb, drought_lvl, area_pct) |> 

  # add year, month & day cols using {lubridate} fxns ----
  # NOTE: this step isn't necessary for our plot, but I'm including as examples of how to extract different date elements from a object of class `Date` using {lubridate} ----
  mutate(year = year(date),
         month = month(date, label = TRUE, abbr = TRUE),
         day = day(date)) |>

  # add drought level conditions names ----
  mutate(drought_lvl_long = factor(drought_lvl,
                            levels = c("D4", "D3", "D2", "D1","D0", "None"),
                            labels = c("(D4) Exceptional", "(D3) Extreme",
                                       "(D2) Severe", "(D1) Moderate", 
                                       "(D0) Abnormally Dry", 
                                       "No Drought"))) |>
  
  # reorder cols ----
  relocate(date, year, month, day, state_abb, drought_lvl, drought_lvl_long, area_pct)
```

```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##       create stacked area plot of CA drought conditions through time     ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


colors <- c("#853904",
            "#FE2500",
            "#FEC002",
            "#FFD866",
            "#FFFC03")

drought_clean |> 
  
  # remove drought_lvl "None" & filter for just CA ----
  filter(drought_lvl != "None",
         state_abb == "CA") |> 
  ggplot(mapping = aes(x = date, y = area_pct, fill = drought_lvl_long)) +
  geom_area(position = position_stack(reverse = TRUE)) +
    scale_fill_manual(values = colors) +
  labs(title = "Drought area in California") +
  theme_minimal() +
  theme(axis.title = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        axis.line = element_line(colour = "#74AAD9"),
        axis.ticks = element_line(colour = "#74AAD9"),
        plot.title = element_text(hjust = 0.5)) +
  scale_x_date(breaks = breaks_pretty(n = 13),
               label = label_date_short(),
               expand = expansion(0.04, 0.01),
               guide = guide_axis(minor.ticks = TRUE)) +
  scale_y_continuous(label = scales::label_percent(scale = 1),
                     expand = c(0, NA))
  

  
  # pipe into ggplot here!
```


